export const ADJUSTMENT_STATUSES = {
  DRAFT: 'DRAFT',
  CONFIRMED: 'CONFIRMED',
  POSTED: 'POSTED',
  CANCELLED: 'CANCELLED',
  REVERSED: 'REVERSED',
};

export const ADJUSTMENT_TYPES = {
  STOCK_COUNT_GAIN: 'STOCK_COUNT_GAIN',
  STOCK_COUNT_LOSS: 'STOCK_COUNT_LOSS',
  DAMAGE: 'DAMAGE',
  EXPIRED: 'EXPIRED',
  QUALITY_HOLD: 'QUALITY_HOLD',
  QUALITY_RELEASE: 'QUALITY_RELEASE',
  SYSTEM_CORRECTION: 'SYSTEM_CORRECTION',
  OTHER: 'OTHER',
};

export const ADJUSTMENT_DIRECTIONS = {
  IN: 'IN',
  OUT: 'OUT',
};

export const ADJUSTMENT_CONDITION_STATUSES = {
  GOOD: 'GOOD',
  DAMAGED: 'DAMAGED',
  HOLD: 'HOLD',
  EXPIRED: 'EXPIRED',
  REJECTED: 'REJECTED',
  RELEASED: 'RELEASED',
  UNKNOWN: 'UNKNOWN',
};

export const POSTABLE_ADJUSTMENT_STATUSES = [
  ADJUSTMENT_STATUSES.DRAFT,
  ADJUSTMENT_STATUSES.CONFIRMED,
];

