export const BARCODE_ENTITY_TYPES = {
  PRODUCT: 'PRODUCT',
  LOCATION: 'LOCATION',
  PALLET: 'PALLET',
  LOT: 'LOT',
  RECEIVING_DOCUMENT: 'RECEIVING_DOCUMENT',
  RECEIVING_LINE: 'RECEIVING_LINE',
  PUTAWAY_DOCUMENT: 'PUTAWAY_DOCUMENT',
  PUTAWAY_LINE: 'PUTAWAY_LINE',
  TRANSFER_DOCUMENT: 'TRANSFER_DOCUMENT',
  TRANSFER_LINE: 'TRANSFER_LINE',
  ADJUSTMENT_DOCUMENT: 'ADJUSTMENT_DOCUMENT',
  ADJUSTMENT_LINE: 'ADJUSTMENT_LINE',
  WITHDRAWAL_REQUEST: 'WITHDRAWAL_REQUEST',
  WITHDRAWAL_REQUEST_LINE: 'WITHDRAWAL_REQUEST_LINE',
  WITHDRAWAL_ALLOCATION: 'WITHDRAWAL_ALLOCATION',
  WITHDRAWAL_ALLOCATION_LINE: 'WITHDRAWAL_ALLOCATION_LINE',
  PICKING_DOCUMENT: 'PICKING_DOCUMENT',
  PICKING_LINE: 'PICKING_LINE',
  DISPATCH_DOCUMENT: 'DISPATCH_DOCUMENT',
  DISPATCH_LINE: 'DISPATCH_LINE',
  USER: 'USER',
  OTHER: 'OTHER',
};

export const BARCODE_TYPES = {
  PRIMARY: 'PRIMARY',
  ALIAS: 'ALIAS',
  SUPPLIER: 'SUPPLIER',
  CUSTOMER: 'CUSTOMER',
  INTERNAL: 'INTERNAL',
  HANDHELD_LABEL: 'HANDHELD_LABEL',
  OTHER: 'OTHER',
};

export const SCAN_CONTEXTS = {
  GENERAL: 'GENERAL',
  RECEIVING: 'RECEIVING',
  PUTAWAY: 'PUTAWAY',
  TRANSFER: 'TRANSFER',
  ADJUSTMENT: 'ADJUSTMENT',
  WITHDRAWAL: 'WITHDRAWAL',
  ALLOCATION: 'ALLOCATION',
  PICKING: 'PICKING',
  DISPATCH: 'DISPATCH',
  STOCK_COUNT: 'STOCK_COUNT',
  LOGIN: 'LOGIN',
  OTHER: 'OTHER',
};

export const SCAN_RESULTS = {
  RESOLVED: 'RESOLVED',
  UNRESOLVED: 'UNRESOLVED',
  AMBIGUOUS: 'AMBIGUOUS',
  ERROR: 'ERROR',
  IGNORED: 'IGNORED',
};

export const SCAN_SOURCES = {
  WEB: 'WEB',
  HANDHELD: 'HANDHELD',
  MOBILE: 'MOBILE',
  API: 'API',
  SYSTEM: 'SYSTEM',
  OTHER: 'OTHER',
};
