export const OPERATION_CHARGE_TYPES = Object.freeze({
  LIFTING: 'LIFTING',
  REPACK: 'REPACK',
  SORTING: 'SORTING',
  LABELING: 'LABELING',
  PALLETIZING: 'PALLETIZING',
  FREEZING_SERVICE: 'FREEZING_SERVICE',
  OTHER: 'OTHER',
});

export const BILLING_BASIS_TYPES = Object.freeze({
  DAILY_WEIGHT: 'DAILY_WEIGHT',
  MONTHLY_AVERAGE_WEIGHT: 'MONTHLY_AVERAGE_WEIGHT',
  MONTH_END_BALANCE_WEIGHT: 'MONTH_END_BALANCE_WEIGHT',
  OPERATION_QUANTITY: 'OPERATION_QUANTITY',
  FIXED_SERVICE: 'FIXED_SERVICE',
});

export const STORAGE_CHARGE_BASIS = Object.freeze({
  GROSS_WEIGHT: 'GROSS_WEIGHT',
  NET_WEIGHT: 'NET_WEIGHT',
  CHARGEABLE_WEIGHT: 'CHARGEABLE_WEIGHT',
  PALLET_COUNT: 'PALLET_COUNT',
});

export const BILLING_PREVIEW_STATUS = Object.freeze({
  PREVIEW: 'PREVIEW',
  READY_FOR_REVIEW: 'READY_FOR_REVIEW',
  NEEDS_RATE_REVIEW: 'NEEDS_RATE_REVIEW',
  INVALID: 'INVALID',
});

export const SUPPORTED_BILLING_EXPORT_FORMATS = Object.freeze({
  CSV_PREVIEW: 'CSV_PREVIEW',
  XLSX_PREVIEW: 'XLSX_PREVIEW',
  JSON_PREVIEW: 'JSON_PREVIEW',
});
