export const DISPATCH_STATUSES = {
  DRAFT: 'DRAFT',
  CONFIRMED: 'CONFIRMED',
  POSTED: 'POSTED',
  CANCELLED: 'CANCELLED',
  REVERSED: 'REVERSED',
};

export const DISPATCH_TYPES = {
  NORMAL: 'NORMAL',
  CUSTOMER_PICKUP: 'CUSTOMER_PICKUP',
  DELIVERY: 'DELIVERY',
  RETURN_TO_CUSTOMER: 'RETURN_TO_CUSTOMER',
  SAMPLE: 'SAMPLE',
  DAMAGE_DISPOSAL: 'DAMAGE_DISPOSAL',
  OTHER: 'OTHER',
};

export const TRANSPORT_TYPES = {
  COMPANY_TRUCK: 'COMPANY_TRUCK',
  CUSTOMER_PICKUP: 'CUSTOMER_PICKUP',
  THIRD_PARTY: 'THIRD_PARTY',
  OTHER: 'OTHER',
};

export const POSTABLE_DISPATCH_STATUSES = [
  DISPATCH_STATUSES.DRAFT,
  DISPATCH_STATUSES.CONFIRMED,
];

