export const HANDHELD_PUTAWAY_SESSION_STATUSES = {
  OPEN: 'OPEN',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
};

export const HANDHELD_PUTAWAY_SCAN_STEPS = {
  DOCUMENT: 'DOCUMENT',
  LINE: 'LINE',
  PRODUCT: 'PRODUCT',
  LOT: 'LOT',
  PALLET: 'PALLET',
  FROM_LOCATION: 'FROM_LOCATION',
  TO_LOCATION: 'TO_LOCATION',
  QTY: 'QTY',
  CONFIRM: 'CONFIRM',
  OTHER: 'OTHER',
};

export const HANDHELD_PUTAWAY_VALIDATION_STATUSES = {
  PENDING: 'PENDING',
  VALID: 'VALID',
  INVALID: 'INVALID',
  WARNING: 'WARNING',
  SKIPPED: 'SKIPPED',
};
