export const MOVEMENT_TYPES = {
  OPENING_BALANCE: 'OPENING_BALANCE',
  RECEIVE: 'RECEIVE',
  PUTAWAY: 'PUTAWAY',
  TRANSFER: 'TRANSFER',
  ADJUST_IN: 'ADJUST_IN',
  ADJUST_OUT: 'ADJUST_OUT',
  PICK_ALLOCATE: 'PICK_ALLOCATE',
  PICK_CONFIRM: 'PICK_CONFIRM',
  RETURN_IN: 'RETURN_IN',
  REVERSE: 'REVERSE',
};

export const STOCK_INBOUND_TYPES = [
  MOVEMENT_TYPES.OPENING_BALANCE,
  MOVEMENT_TYPES.RECEIVE,
  MOVEMENT_TYPES.ADJUST_IN,
  MOVEMENT_TYPES.RETURN_IN,
];

export const STOCK_OUTBOUND_TYPES = [
  MOVEMENT_TYPES.ADJUST_OUT,
  MOVEMENT_TYPES.PICK_CONFIRM,
];

export const STOCK_TRANSFER_TYPES = [
  MOVEMENT_TYPES.PUTAWAY,
  MOVEMENT_TYPES.TRANSFER,
];

export const ALLOCATION_TYPES = [
  MOVEMENT_TYPES.PICK_ALLOCATE,
  MOVEMENT_TYPES.PICK_CONFIRM,
];

