export const PICKING_STATUSES = {
  DRAFT: 'DRAFT',
  RELEASED: 'RELEASED',
  IN_PROGRESS: 'IN_PROGRESS',
  PICKED: 'PICKED',
  CANCELLED: 'CANCELLED',
};

export const PICKING_METHODS = {
  MANUAL: 'MANUAL',
  FIFO: 'FIFO',
  FEFO: 'FEFO',
  HANDHELD_SCAN: 'HANDHELD_SCAN',
  SYSTEM_SUGGESTED: 'SYSTEM_SUGGESTED',
};

export const CONFIRMABLE_PICKING_STATUSES = [
  PICKING_STATUSES.DRAFT,
  PICKING_STATUSES.RELEASED,
  PICKING_STATUSES.IN_PROGRESS,
];

