export const PUTAWAY_STATUSES = {
  DRAFT: 'DRAFT',
  CONFIRMED: 'CONFIRMED',
  POSTED: 'POSTED',
  CANCELLED: 'CANCELLED',
  REVERSED: 'REVERSED',
};

export const POSTABLE_PUTAWAY_STATUSES = [
  PUTAWAY_STATUSES.DRAFT,
  PUTAWAY_STATUSES.CONFIRMED,
];

