export const RECEIVING_STATUSES = {
  DRAFT: 'DRAFT',
  CONFIRMED: 'CONFIRMED',
  POSTED: 'POSTED',
  CANCELLED: 'CANCELLED',
  REVERSED: 'REVERSED',
};

export const RECEIVING_TYPES = {
  NORMAL: 'NORMAL',
  RETURN: 'RETURN',
  OPENING_BALANCE: 'OPENING_BALANCE',
  ADJUSTMENT_IN: 'ADJUSTMENT_IN',
};

export const RECEIVING_CONDITION_STATUSES = {
  GOOD: 'GOOD',
  DAMAGED: 'DAMAGED',
  HOLD: 'HOLD',
  REJECTED: 'REJECTED',
};

export const POSTABLE_RECEIVING_STATUSES = [
  RECEIVING_STATUSES.DRAFT,
  RECEIVING_STATUSES.CONFIRMED,
];

