export const STOCK_COUNT_STATUSES = {
  DRAFT: 'DRAFT',
  IN_PROGRESS: 'IN_PROGRESS',
  COUNTED: 'COUNTED',
  APPROVED: 'APPROVED',
  CANCELLED: 'CANCELLED',
  ADJUSTMENT_CREATED: 'ADJUSTMENT_CREATED',
};

export const STOCK_COUNT_TYPES = {
  FULL_COUNT: 'FULL_COUNT',
  CYCLE_COUNT: 'CYCLE_COUNT',
  LOCATION_COUNT: 'LOCATION_COUNT',
  PRODUCT_COUNT: 'PRODUCT_COUNT',
  LOT_COUNT: 'LOT_COUNT',
  PALLET_COUNT: 'PALLET_COUNT',
  ADHOC: 'ADHOC',
};

export const STOCK_COUNT_LINE_STATUSES = {
  PENDING: 'PENDING',
  COUNTED: 'COUNTED',
  VARIANCE: 'VARIANCE',
  ZERO_COUNT: 'ZERO_COUNT',
  SKIPPED: 'SKIPPED',
};

export const COMPLETABLE_STOCK_COUNT_STATUSES = [
  STOCK_COUNT_STATUSES.DRAFT,
  STOCK_COUNT_STATUSES.IN_PROGRESS,
];
