export const TRANSFER_STATUSES = {
  DRAFT: 'DRAFT',
  CONFIRMED: 'CONFIRMED',
  POSTED: 'POSTED',
  CANCELLED: 'CANCELLED',
  REVERSED: 'REVERSED',
};

export const TRANSFER_TYPES = {
  INTERNAL: 'INTERNAL',
  ROOM_TRANSFER: 'ROOM_TRANSFER',
  PALLET_TRANSFER: 'PALLET_TRANSFER',
  LOCATION_TRANSFER: 'LOCATION_TRANSFER',
  QUALITY_HOLD_TRANSFER: 'QUALITY_HOLD_TRANSFER',
};

export const POSTABLE_TRANSFER_STATUSES = [
  TRANSFER_STATUSES.DRAFT,
  TRANSFER_STATUSES.CONFIRMED,
];

