export const USER_ROLES = {
  ADMIN: 'ADMIN',
  MANAGER: 'MANAGER',
  WAREHOUSE_SUPERVISOR: 'WAREHOUSE_SUPERVISOR',
  WAREHOUSE_STAFF: 'WAREHOUSE_STAFF',
  VIEWER: 'VIEWER',
  AUDITOR: 'AUDITOR',
};

export const ROLE_LABELS = {
  [USER_ROLES.ADMIN]: 'Admin',
  [USER_ROLES.MANAGER]: 'Manager',
  [USER_ROLES.WAREHOUSE_SUPERVISOR]: 'Warehouse Supervisor',
  [USER_ROLES.WAREHOUSE_STAFF]: 'Warehouse Staff',
  [USER_ROLES.VIEWER]: 'Viewer',
  [USER_ROLES.AUDITOR]: 'Auditor',
};

export const INVENTORY_VIEW_ROLES = [
  USER_ROLES.ADMIN,
  USER_ROLES.MANAGER,
  USER_ROLES.WAREHOUSE_SUPERVISOR,
  USER_ROLES.WAREHOUSE_STAFF,
  USER_ROLES.VIEWER,
  USER_ROLES.AUDITOR,
];

export const INVENTORY_POST_ROLES = [
  USER_ROLES.ADMIN,
  USER_ROLES.MANAGER,
  USER_ROLES.WAREHOUSE_SUPERVISOR,
  USER_ROLES.WAREHOUSE_STAFF,
];

export const AUDIT_VIEW_ROLES = [
  USER_ROLES.ADMIN,
  USER_ROLES.AUDITOR,
];

export const ADMIN_ROLES = [
  USER_ROLES.ADMIN,
];

