export const WITHDRAWAL_ALLOCATION_STATUSES = {
  DRAFT: 'DRAFT',
  CONFIRMED: 'CONFIRMED',
  POSTED: 'POSTED',
  CANCELLED: 'CANCELLED',
  REVERSED: 'REVERSED',
};

export const WITHDRAWAL_ALLOCATION_METHODS = {
  MANUAL: 'MANUAL',
  FIFO: 'FIFO',
  FEFO: 'FEFO',
  SYSTEM_SUGGESTED: 'SYSTEM_SUGGESTED',
};

export const POSTABLE_WITHDRAWAL_ALLOCATION_STATUSES = [
  WITHDRAWAL_ALLOCATION_STATUSES.DRAFT,
  WITHDRAWAL_ALLOCATION_STATUSES.CONFIRMED,
];

