export const WITHDRAWAL_REQUEST_STATUSES = {
  DRAFT: 'DRAFT',
  CONFIRMED: 'CONFIRMED',
  ALLOCATED: 'ALLOCATED',
  PARTIALLY_ALLOCATED: 'PARTIALLY_ALLOCATED',
  PICKING: 'PICKING',
  PICKED: 'PICKED',
  DISPATCHED: 'DISPATCHED',
  CANCELLED: 'CANCELLED',
  CLOSED: 'CLOSED',
};

export const WITHDRAWAL_TYPES = {
  NORMAL: 'NORMAL',
  CUSTOMER_PICKUP: 'CUSTOMER_PICKUP',
  DELIVERY: 'DELIVERY',
  RETURN_TO_CUSTOMER: 'RETURN_TO_CUSTOMER',
  SAMPLE: 'SAMPLE',
  DAMAGE_DISPOSAL: 'DAMAGE_DISPOSAL',
  OTHER: 'OTHER',
};

export const WITHDRAWAL_PRIORITIES = {
  LOW: 'LOW',
  NORMAL: 'NORMAL',
  HIGH: 'HIGH',
  URGENT: 'URGENT',
};

export const CONFIRMABLE_WITHDRAWAL_REQUEST_STATUSES = [
  WITHDRAWAL_REQUEST_STATUSES.DRAFT,
];

